openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Product API
  description: API para gestionar productos

paths:
  /products:
    get:
      summary: Obtiene una lista de productos
      parameters:
        - name: nombre
          in: query
          schema:
            type: string
          description: Nombre del producto a buscar
        - name: minPrice
          in: query
          schema:
            type: integer
          description: Precio mínimo del producto
        - name: maxPrice
          in: query
          schema:
            type: integer
          description: Precio máximo del producto
        - name: sort
          in: query
          schema:
            type: string
            enum: [asc, desc]
          description: Ordenar los productos por precio
      responses:
        "200":
          description: Una lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Crea un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "201":
          description: Producto creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /products/{id}:
    get:
      summary: Obtiene un producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Un producto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: Producto no encontrado
    put:
      summary: Actualiza un producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "200":
          description: Producto actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: Producto no encontrado
    delete:
      summary: Elimina un producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Producto eliminado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Product:
      type: object
      properties:
        nombre:
          type: string
        precio:
          type: integer
        foto:
          type: string
        tags:
          type: array
          items:
            type: string
        venta:
          type: boolean
